name: ⭐ Feature Request
description: Submit a feature request
body:
  - type: checkboxes
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if a feature request already exists for the feature you are requesting.
      options:
      - label: I searched the existing feature requests and did not find anything similar.
        required: true
  - type: markdown
    attributes:
      value: |
        Thanks for submitting a feature request! Please fill out the sections below.
  - type: textarea
    id: the-feature-request
    attributes:
      label: The feature request
      description:
        Write a clear and concise description of what the feature or problem is.
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: Share how this will benefit VCANDY and its users.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description:
        Please include any other context, like screenshots or mockups, if
        applicable.
